title: Melon's bitcamp life
author:
  name: Melon-jy-Yi
  email: crazygizmowh@nate.com
description: > # this means to ignore newlines until "show_excerpts:"
  Again my site

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/crazygizmowh" }
    - { platform: github,         user_url: "https://github.com/melon-jy" }
    - { platform: instagram,      user_url: "https://www.instagram.com/meltube2020" }
    - { platform: twitter,        user_url: "https://twitter.com/Melon_Meltube" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@valorant7180/videos" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
